manipulator:
  ros__parameters:
    robot_type: "manipulator"

    # Topic Names
    camera_topic: "/camera/image_raw"
    state_topic: "/joint_states"
    teleop_topic: "/teleop_cmd"
    command_topic: "/joint_trajectory_controller/joint_trajectory"

    # Neural Network Dimensions
    state_dim: 6
    action_dim: 6


turtlebot:
  ros__parameters:
    robot_type: "turtlebot"

    camera_topic: "/camera/image_raw"
    state_topic: "/odom"
    teleop_topic: "/cmd_vel_teleop"
    command_topic: "/turtle1/cmd_vel"

    state_dim: 2
    action_dim: 2